sudo: false

language: haskell
ghc: 7.10.2

cache:
  directories:
    - $HOME/.stack

env:
  matrix:
    - STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - hlint

before_install:
  - export TERM=dumb

install:
  - travis_retry wget https://github.com/AlDanial/cloc/releases/download/1.64/cloc-1.64.pl
  - mv cloc-1.64.pl cloc
  - chmod +x cloc
  - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz
  - tar xzf stack-0.1.6.0-linux-x86_64.tar.gz
  - mv stack-0.1.6.0-linux-x86_64/stack stack
  - chmod +x stack
  - travis_retry ./stack setup
  - travis_retry ./stack install --only-snapshot -j4 --verbosity info

script:
  - ./cloc .
  - hlint .; echo
  - grep -r --include=\*\.{hs,lhs} FIXME . | wc
  - ./stack haddock
  - ./stack clean
  - ./stack test --coverage
