sudo: false

language: haskell
ghc: 7.10.2

cache:
  directories:
    - $HOME/.stack

env:
  matrix:
    - STACK_YAML=stack.yaml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cloc

install:
  - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-x86_64-linux.tar.gz
  - tar xzf stack-0.1.6.0-x86_64-linux.tar.gz
  - mv stack-0.1.6.0-x86_64-linux/stack stack
  - chmod +x stack
  - travis_retry ./stack setup
  - travis_retry ./stack install -j4 --verbosity info hlint
  - travis_retry ./stack install --only-snapshot -j4 --verbosity info

script:
  - ./stack build
  - ./stack clean
  - ./stack test --coverage
  - ./stack haddock
  - hlint .
  - grep -r --include=\*\.{hs,lhs} FIXME . | wc
  - cloc --quiet --include-lang Haskell
